### ISSUE TITLE
Retornar destinos, no sus nombres

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/tpBarrileteCosmico#1]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/empresa.wlk#L8

No era necesario que mapearan los destinos para retornar solo sus nombres. De hecho, si después, por ejemplo, quisieran aplicarle un descuento a los destinos importantes, no podrían usar este método porque solamente devuelve una lista de strings.

**Comment by tomi-iglesias** [comment]
Corregido!
