### ISSUE TITLE
Consistencia en los getters

### ISSUE THREAD

**Issue by LucasZibell** [tomi-iglesias/tpBarrileteCosmico#11]
Vi que en algunos lugares del codigo. Por ejemplo en la clase `Usuario` cuando necesitan acceder a un valor de la clase a veces usan el getter `self.getDinero()` y a veces usan directamente `dineroEnCuenta`. Ambas estan bien, lo que si pedimos es que cuando hagan las soluciones elijan una de las dos formas y sean consitentes con esa

**Comment by tomi-iglesias** [comment]
corregido
