### ISSUE TITLE
Que pasa si el descuento es mayor al 100%?

### ISSUE THREAD

**Issue by LucasZibell** [tomi-iglesias/tpBarrileteCosmico#12]
En el metodo estan multiplicando y restando el precio por el descuento.
```
method aplicarDescuento(unPorcentaje){
		precio -= self.getPrecio() * unPorcentaje
		self.getEquipajes().add("Certificado de descuento")
	}
```
Creo que deberiamos realizar alguna validacion aca para evitar que queden precios negativos. En cualquier caso, deberia quedar 0 como precio y ser un viaje gratuito

**Comment by tomi-iglesias** [comment]
corregido
