### ISSUE TITLE
Estan sobredelegando

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/tpBarrileteCosmico#2]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/destinos.wlk#L22

Fijense que lo único que hace este método es un `.add` a la lista de equipaje, no es necesario que declaren un nuevo método para eso, simplemente tendrían que hacer `equipajeImprescindible.add(loQueSea)` cuando quieren agregar algo.

**Comment by josibuttazzoni** [comment]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/usuarios.wlk#L22
Lo mismo aca

**Comment by josibuttazzoni** [comment]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/destinos.wlk#L26
Y aca

**Comment by scupolo** [comment]
okey, gracias

**Comment by tomi-iglesias** [comment]
Corregidos
