### ISSUE TITLE
Expresividad

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/tpBarrileteCosmico#3]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/destinos.wlk#L30

La idea de este método es saber si el destino es peligroso o no, entonces, en lugar de llamarse `contieneVacunaEnEquipaje()` podría llamarse `esPeligroso()`.

**Comment by tomi-iglesias** [comment]
corregido
