### ISSUE TITLE
No se limiten al enunciado

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/tpBarrileteCosmico#4]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/destinos.wlk#L31

¿Qué pasaría en caso de que se agregara un destino que en su equipaje contara con una vacuna que no es ni la B ni la gripal? ¿Tendría que ser peligroso o no?

**Comment by tomi-iglesias** [comment]
Corregido!
