### ISSUE TITLE
Repeticion de logica

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/tpBarrileteCosmico#7]
https://github.com/tomi-iglesias/tpBarrileteCosmico/blob/445d7c5d37f32e19855dcd8c913db31a1e2922be/src/tests/tests.wtest#L44

Fijense que acá están chequeando lo mismo con todos los destinos y podrían usar `all` directamente para evitarlo.

**Comment by tomi-iglesias** [comment]
corregido
