### ISSUE TITLE
Valor absoluto de la distancia

### ISSUE THREAD

**Issue by LucasZibell** [tomi-iglesias/tpBarrileteCosmico#8]
Aca se puede evitar el if y la multiplicacion usando el absoluto de un numero `abs`
```
	method calcularDistanciaA(unaLocalidad){
		var distancia = self.getUbicacion() - unaLocalidad.getUbicacion() 		
		if (distancia > 0){
			return distancia
		} else {
			return distancia * -1
		}
	}
```
https://docs.google.com/document/d/e/2PACX-1vTlLkakSbp6ubcIq00PU4-Z96tg8CUSc8bO793_uftmiGjfkSn7Ug-F_y0-ieIWG6aWfuoHLJrRL8Fd/pub

**Comment by tomi-iglesias** [comment]
Corregido!
